language: en-us
commandAliases:
  - "fpm"
  - "fp"
randomNameLength: 10
defaultSpawnLocation:
  world: "world"
  x: 0
  y: 70
  z: 0
  pitch: 0
  yaw: 0
#Please install the WorldEdit or FastAsyncWorldEdit plugin before starting!
areaStressTesters: false