name: FakePlayerMaker
version: '${project.version}'
main: org.lins.mmmjjkx.fakeplayermaker.FakePlayerMaker
api-version: "1.18"
website: https://github.com/LinsMinecraftStudio/FakePlayerMaker
libraries:
  - "net.bytebuddy:byte-buddy:1.14.8"

depend: [ "Polymer" ]
softdepend: [ "FastAsyncWorldEdit", "WorldEdit", "ProtocolLib" ]

commands:
  fakeplayermaker:
    description: the main command of FakePlayerMaker
    aliases: [ "fpm" ]

permissions:
  fakeplayermaker.command:
    description: allows you to use /fakeplayermaker command
    default: op
  fakeplayermaker.command.stress:
    description: allows you to use /fakeplayermaker stress command
    default: op