language: en-us
namePrefix: "fake_"
randomNameLength: 10
player:
  invulnerable: false
  canPickupItems: false
  collision: false
  respawnBack: true
defaultSpawnLocation:
  world: "world"
  x: 0
  y: 70
  z: 0
  pitch: 0
  yaw: 0
#Run commands after join (by fake player)
#You can put some commands about login plugin here.
runCMDAfterJoin:
  - "register 123723123 123723123"
  - "login 123723123"
  - "chat:Hi, I am %player%"
#Run commands after join (by console)
runCMDConsoleAfterJoin:
  - "broadcast Welcome %player%!!"
#Please install the WorldEdit or FastAsyncWorldEdit plugin before turn it on!
#Recommended creating an open area to create a stress tester.
areaStressTesters: false