name: FakePlayerMaker
version: '${project.version}'
main: org.lins.mmmjjkx.fakeplayermaker.FakePlayerMaker
api-version: "1.19"
website: https://github.com/LinsMinecraftStudio/FakePlayerMaker
bootstrapper: org.lins.mmmjjkx.fakeplayermaker.paper.FPMBootStrap
loader: org.lins.mmmjjkx.fakeplayermaker.paper.FPMLoader
has-open-classloader: true

dependencies:
  - name: Polymer
    required: true
    bootstrap: false
  - name: WorldEdit
    required: false
    bootstrap: false
  - name: FastAsyncWorldEdit
    required: false
    bootstrap: false
  - name: ProtocolLib
    required: false
    bootstrap: false
permissions:
  fakeplayermaker.command:
    description: allows you to use /fakeplayermaker command